---
abstract: 'Common Widgets using SDL'
author:
  - 'Dustin Mays, garu, Zpmorgan, kthakore, FROGGS'
build_requires:
  SDL: 2.523
  Test::More: 0.88
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SDLx-Widget
provides:
  SDLx::Widget:
    file: lib/SDLx/Widget.pm
    version: 0.071
  SDLx::Widget::Menu:
    file: lib/SDLx/Widget/Menu.pm
  SDLx::Widget::Textbox:
    file: lib/SDLx/Widget/Textbox.pm
requires:
  Clipboard: 0
  Mouse: 0
  SDL: 2.523
resources:
  bugtracker: http://sdlperl.ath.cx/projects/SDLPerl/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/PerlGameDev/SDLx-Widget
version: 0.071
